---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: sort-simple-yaml
      - id: check-merge-conflict
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.7.1
    hooks:
      - id: check-jsonschema
        name: "Validate renovate config"
        files: ^renovate.json$
        args: ["--schemafile", "https://docs.renovatebot.com/renovate-schema.json"]
      - id: check-jsonschema
        name: "Validate package.json"
        files: ^package.json$
        args: ["--schemafile", "https://json.schemastore.org/package.json"]
  - repo: https://github.com/killermoehre/renovate-pre-commit-hooks
    rev: 1.0.0
    hooks:
      - id: renovate-config-validator
